# tests/test_stage2.py
"""
Comprehensive test suite for Stage 2 MONITOR crew.
Tests all 12 core requirements from Section 14:
1. SAE_MISCODED critical escalation for AESHOSP=Y and AESER=N
2. Hy's Law screening baseline elevation -> MONITORING_ONLY
3. Pre-dose AE -> Data query (not medical escalation)
4. Zero duplicate queries on cycle re-run
5. Zero duplicate escalations on cycle re-run
6. REJECTED escalation -> monitoring only, never re-escalated
7. CLARIFY -> answers from graph, resubmits -> APPROVED
8. Multi-cycle flagged subject (>= 2 cycles) -> auto-escalation
9. Recurring site issues -> site flag
10. Protocol amendment applies new version rules
11. Real-time trace generated by every node
12. End-to-end cycle execution & valid report
"""

import os
import unittest
from pathlib import Path

from stage1.atlas import Atlas, StudyGraph
from stage2.crew import ReviewCrew
from stage2.models import EscalationDraft, Finding, Query, ReviewReport


class TestStage2Crew(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        data_dir = "hackathon-data"
        cls.graph = StudyGraph(data_dir)
        cls.atlas = Atlas(cls.graph)
        cls.hub_url = "http://127.0.0.1:8000"
        cls.gateway_url = "http://127.0.0.1:8001"
        cls.team_key = "test_team"

    def setUp(self):
        # Create fresh crew with clean memory before each test
        self.crew = ReviewCrew(
            self.hub_url,
            self.gateway_url,
            self.team_key,
            self.atlas,
            memory_path="test_stage2_memory.json",
        )
        self.crew.memory.reset()

    def tearDown(self):
        self.crew.memory.reset()

    def test_01_sae_miscoded_escalation(self):
        """Test 1: AESHOSP=Y and AESER=N produces SAE_MISCODED critical escalation."""
        report = self.crew.run_cycle(cut=6, protocol_version=2)
        sae_escs = [e for e in report.escalations if e.get("code") == "SAE_MISCODED"]
        self.assertGreater(len(sae_escs), 0, "Should have detected at least one SAE_MISCODED")
        sae = sae_escs[0]
        self.assertEqual(sae.get("severity"), "CRITICAL")
        self.assertIn("hospital", sae.get("summary", "").lower())
        self.assertIn("24-hour", sae.get("summary", "").lower())

    def test_02_hys_law_screening_elevated_monitoring_only(self):
        """Test 2: Liver signal with elevated screening transaminases -> MONITORING_ONLY."""
        report = self.crew.run_cycle(cut=6, protocol_version=2)
        # Subjects with high screening transaminases (e.g. 042-S07-001, 042-S09-001) should remain monitoring-only
        monitoring_hys = [
            m for m in report.monitoring_only
            if m.get("finding", {}).get("code") == "HYS_LAW_CANDIDATE"
        ]
        self.assertGreater(len(monitoring_hys), 0, "Should have liver signals kept in monitoring-only")
        reasons = [m.get("reason", "") for m in monitoring_hys]
        self.assertTrue(
            any("screening ALT" in r or "Screening ALT" in r or "Baseline" in r for r in reasons),
            f"Rationale should document pre-existing elevated screening transaminases: {reasons}",
        )

    def test_03_predose_ae_data_query(self):
        """Test 3: Event occurring before first dose produces a data query (not medical escalation)."""
        report = self.crew.run_cycle(cut=6, protocol_version=2)
        predose_queries = [
            q for q in report.queries
            if "before first dose" in q.get("text", "").lower()
        ]
        self.assertGreater(len(predose_queries), 0, "Pre-dose AE should trigger a data query")
        # Ensure it was NOT drafted as a medical escalation
        predose_escs = [e for e in report.escalations if e.get("code") == "PRE_DOSE_AE"]
        self.assertEqual(len(predose_escs), 0, "Pre-dose AE should not be a medical escalation")

    def test_04_duplicate_query_prevention(self):
        """Test 4: Running pipeline twice on same cut produces ZERO new queries in cycle 2."""
        report1 = self.crew.run_cycle(cut=6, protocol_version=2)
        self.assertGreater(len(report1.queries), 0, "Cycle 1 should produce queries")

        report2 = self.crew.run_cycle(cut=6, protocol_version=2)
        self.assertEqual(len(report2.queries), 0, f"Cycle 2 should produce 0 new queries, got {len(report2.queries)}")

    def test_05_duplicate_escalation_prevention(self):
        """Test 5: Running pipeline twice on same cut produces ZERO new escalations in cycle 2."""
        report1 = self.crew.run_cycle(cut=6, protocol_version=2)
        self.assertGreater(len(report1.escalations), 0, "Cycle 1 should produce escalations")

        report2 = self.crew.run_cycle(cut=6, protocol_version=2)
        self.assertEqual(len(report2.escalations), 0, f"Cycle 2 should produce 0 new escalations, got {len(report2.escalations)}")

    def test_06_rejected_escalation_stays_in_monitoring(self):
        """Test 6: A REJECTED escalation response puts item into MONITORING_ONLY and prevents re-escalation."""
        # Manually record a rejection in memory
        self.crew.memory.record_escalation(
            "SAE_MISCODED",
            "042-S02-004",
            {
                "id": "E-TEST",
                "code": "SAE_MISCODED",
                "usubjid": "042-S02-004",
                "decision": "REJECTED",
                "reason": "Overnight stay was social observation, not clinical admission.",
            },
        )
        self.assertTrue(self.crew.memory.is_rejected("SAE_MISCODED", "042-S02-004"))

        # Run cycle — 042-S02-004 must NOT be escalated, should appear in monitoring_only
        report = self.crew.run_cycle(cut=6, protocol_version=2)
        sae_escs = [
            e for e in report.escalations
            if e.get("code") == "SAE_MISCODED" and e.get("usubjid") == "042-S02-004"
        ]
        self.assertEqual(len(sae_escs), 0, "Rejected finding must not be re-escalated")

        rejected_mon = [
            m for m in report.monitoring_only
            if m.get("finding", {}).get("usubjid") == "042-S02-004"
        ]
        self.assertGreater(len(rejected_mon), 0, "Rejected finding must be retained in monitoring_only")
        self.assertIn("Previously rejected", rejected_mon[0].get("reason", ""))

    def test_07_clarify_triggers_graph_resubmission_approved(self):
        """Test 7: CLARIFY response triggers graph lookup and resubmission ending in APPROVED."""
        draft = EscalationDraft(
            id="E-CLARIFY-TEST",
            code="HYS_LAW_CANDIDATE",
            usubjid="042-S01-001",
            site_id="S01",
            severity="HIGH",
            summary="Potential Hy's law criteria met",
            evidence=[],
            alternatives=["Report to safety", "Continue dosing"],
        )
        processed = self.crew.node_human_gate.run(
            [draft],
            cut=1,
            protocol_version=1,
            trace_fn=lambda node, act, txt, meta=None: None,
        )
        self.assertEqual(len(processed), 1)
        res = processed[0]
        self.assertIsNotNone(res.clarification_requested, "Should have recorded clarify question")
        self.assertIsNotNone(res.clarification_response, "Should have retrieved clarification answer from graph")
        self.assertEqual(res.decision, "APPROVED", "After clarification resubmission, decision must be APPROVED")

    def test_08_multicycle_subject_flag_escalation(self):
        """Test 8: Subject flagged in two cycles triggers automatic escalation on the second cycle."""
        subject_id = "042-S01-001"
        # Record flag in Cycle 1
        self.crew.memory.record_subject_flag(subject_id, cut=1)
        self.assertEqual(self.crew.memory.get_subject_cycle_count(subject_id), 1)

        # In Cycle 2, subject has count >= 2
        self.crew.memory.record_subject_flag(subject_id, cut=2)
        self.assertEqual(self.crew.memory.get_subject_cycle_count(subject_id), 2)

        # Create finding with HIGH severity
        f = Finding(
            code="COMPLIANCE_NON_ATTENDANCE",
            category="compliance",
            usubjid=subject_id,
            site_id="S01",
            severity="HIGH",
            summary="Repeated missed assessments",
        )
        drafts, _ = self.crew.node_medical_review.run(
            [f],
            cut=2,
            protocol_version=1,
            trace_fn=lambda node, act, txt, meta=None: None,
        )
        recurring_drafts = [
            d for d in drafts
            if d.code == "RECURRING_SUBJECT_SIGNAL" and d.usubjid == subject_id
        ]
        self.assertGreater(len(recurring_drafts), 0, "Multi-cycle flagged subject must trigger escalation")

    def test_09_recurring_site_problem_flag(self):
        """Test 9: Recurring site problem accumulates and triggers site flag."""
        site_id = "S12"
        self.crew.memory.record_site_issue(site_id, cut=1, issue_type="visit_window")
        self.assertEqual(len(self.crew.memory.get_site_flags()), 0)

        # Second cut with issue at same site triggers RECURRING_PROBLEMS flag
        self.crew.memory.record_site_issue(site_id, cut=2, issue_type="dose")
        flags = self.crew.memory.get_site_flags()
        self.assertIn(site_id, flags)
        self.assertEqual(flags[site_id]["status"], "RECURRING_PROBLEMS")
        self.assertIn(1, flags[site_id]["cycles_affected"])
        self.assertIn(2, flags[site_id]["cycles_affected"])

    def test_10_protocol_amendment_applies_new_rules(self):
        """Test 10: Protocol amendment applies new version rules (e.g. visit window / renal exclusions)."""
        findings_v1 = self.crew.node_detect.run(
            cut=6,
            protocol_version=1,
            trace_fn=lambda node, act, txt, meta=None: None,
        )
        findings_v2 = self.crew.node_detect.run(
            cut=6,
            protocol_version=2,
            trace_fn=lambda node, act, txt, meta=None: None,
        )
        # Protocol v2 introduced renal creatinine exclusion (> 1.5 mg/dL)
        renal_v1 = [f for f in findings_v1 if f.code == "RENAL_EXCLUSION_DEVIATION"]
        renal_v2 = [f for f in findings_v2 if f.code == "RENAL_EXCLUSION_DEVIATION"]
        self.assertEqual(len(renal_v1), 0, "Protocol v1 did not have renal exclusion")
        self.assertGreater(len(renal_v2), 0, "Protocol v2 has active renal exclusion")

    def test_11_realtime_trace_generation(self):
        """Test 11: Real-time trace is generated by every node during execution."""
        report = self.crew.run_cycle(cut=6, protocol_version=2)
        self.assertGreater(len(report.trace), 0, "Trace should not be empty")

        nodes_in_trace = {
            entry["node"]
            for entry in report.trace_entries
            if "node" in entry
        }
        expected_nodes = {"detect", "medical_review", "data_manager", "compliance", "human_gate", "execute"}
        for node in expected_nodes:
            self.assertIn(node, nodes_in_trace, f"Node {node} must emit trace events during execution")

    def test_12_end_to_end_cycle(self):
        """Test 12: End-to-end cycle completes and produces valid ReviewReport."""
        report = self.crew.run_cycle(cut=6, protocol_version=2)
        self.assertIsInstance(report, ReviewReport)
        self.assertEqual(report.execution_status, "COMPLETE")
        self.assertEqual(report.cut, 6)
        self.assertEqual(report.protocol_version, 2)
        self.assertGreater(report.findings_summary["total"], 0)
        self.assertGreater(len(report.escalations), 0)
        self.assertGreater(len(report.queries), 0)
        self.assertGreater(len(report.deviations), 0)
        self.assertGreater(len(report.trace), 0)


if __name__ == "__main__":
    unittest.main()
